### ISSUE TITLE
Angular 16 Support

### ISSUE THREAD

**Issue by Timmeeeey** [PerfectMemory/ngx-contextmenu#23]
Please support Angular 16.

**Comment by sroucheray** [comment]
Hi @Timmeeeey,

It is planned ! Just still have some issues updating storybook. The Angular 16 compatible version is not released yet, still alpha.

**Comment by sroucheray** [comment]
I just released a 16.0.0-alpha.0 version. No change in the de code, just an update to Angular 16 and latest Storybook alpha version.

**Comment by Timmeeeey** [comment]
Hi @sroucheray,

I think you forgot to change the peerDependencies.

https://github.com/PerfectMemory/ngx-contextmenu/blob/045c0081073c589ece95fb39e203e7f85574eab1/projects/ngx-contextmenu/package.json#L23-L27

**Comment by sroucheray** [comment]
Dammit ! This is not the first time. Thanks. 16.0.0-alpha.1 is in the CI

**Comment by michelebenolli** [comment]
Hi Stéphane, what is missing for full support? Is it planned shortly?

**Comment by sroucheray** [comment]
Hi @michelebenolli, nothing. I usually wait for some weeks for any feedbacks before release. I am going to do it now.

**Comment by sroucheray** [comment]
v16.0.0 released https://www.npmjs.com/package/@perfectmemory/ngx-contextmenu?activeTab=versions
